spring:
  application:
    name: @project.name@
  datasource:
    url: jdbc:h2:mem:standard;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    schema: classpath:schema-h2.sql

batch:
  datasource:
    url: jdbc:hsqldb:mem:batch

logging:
  level:
    sql: info
