spring:
  application:
    name: @project.name@
  datasource:
    url: jdbc:h2:mem:standard;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    hikari:
      pool-name: HikariPool Spring Datasource
  sql:
    init:
      mode: always
      platform: h2

batch:
  datasource:
    url: jdbc:hsqldb:mem:batch
    hikari:
      pool-name: HikariPool Batch

logging:
  level:
    sql: info
