= Guidelines for Spring Boot
Frank Rahn <frank@frank-rahn.de>
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:badges:
endif::[]
:toc:
:toclevels: 3
:toc-title: pass:[<h2>Inhaltsverzeichnis</h2>]
:toc-placement!:
:sectanchors:
:sectnums:
:icons: font

ifdef::badges[]
image:https://img.shields.io/badge/license-Apache_License_2-blue.svg[title="Apache License 2", alt="Apache License 2", link="https://www.apache.org/licenses/LICENSE-2.0"]
image:https://github.com/frank-rahn/guidelines-spring-boot/workflows/build/badge.svg[title="Build Status",alt="Build Status", link="https://github.com/frank-rahn/guidelines-spring-boot/actions?query=workflow%3Abuild"]
image:https://sonarcloud.io/api/project_badges/measure?project=frank-rahn_guidelines-spring-boot&metric=alert_status[title="Quality Gate Status", alt="Quality Gate Status", link="https://sonarcloud.io/dashboard?id=frank-rahn_guidelines-spring-boot"]
endif::[]

toc::[]

== Beschreibung

In diesem Repository befinden sich Projekte als Vorlagen rund um das Thema Spring Boot.

=== Java Style Guide

In allen Modulen wird der Java Style Guide aus den https://google.github.io/styleguide/[Google Style Guides] genutzt.

Zusätzlich wird das Tool https://projectlombok.org/[Lombok] eingesetzt.

=== CI

Alle Module werden mit https://github.com/features/actions[GitHub Actions] gebaut.

=== Code Qualität

Alle Module besitzen Unit-Tests, die mit https://junit.org/junit5/[JUnit5], https://joel-costigliola.github.io/assertj/[AssertJ] und https://site.mockito.org/[Mockito] sowie Test-Utilities der eingesetzen Spring-Projekte.

Die Code-Qualität wird beim CI mit https://sonarcloud.io/dashboard?id=frank-rahn_guidelines-spring-boot[SonarCloud] überprüft.

=== Docker-Image

Jedes Modul wird mit dem Google Maven Plugin https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin[jib-maven-plugin] in ein Docker-Image überführt.

== Module

=== App-Core

Es wird mit Spring Boot eine Anwendung umgesetzt, die einige Dinge erledigt und sich wieder beendet - dabei wird ein entsprechender `exit code` zurückgeliefert.

link:guideline-springboot-app-core/README.adoc[Mehr zur Anwendung]

=== App-JDBC

Es wird mit Spring Boot eine Anwendung umgesetzt, die mit Spring Data JDBC auf eine Datenbank zugreift.

link:guideline-springboot-app-jdbc/README.adoc[Mehr zur Anwendung]

=== App-JPA

Es wird mit Spring Boot eine Anwendung umgesetzt, die mit Spring Data JPA auf eine Datenbank zugreift.

link:guideline-springboot-app-jpa/README.adoc[Mehr zur Anwendung]

=== Batch

Eine Spring Batch Anwendung mit Spring Boot.

link:guideline-springboot-batch/README.adoc[Mehr zur Anwendung]

=== Rest

Es wird mit Spring Boot ein Rest-Service umgesetzt.

link:guideline-springboot-rest/README.adoc[Mehr zur Anwendung]

=== Web

Es wird mit Spring Boot eine Webanwendung umgesetzt.

link:guideline-springboot-web/README.adoc[Mehr zur Anwendung]

== Hilfen

link:HELP.adoc[Getting Started]

Falls mit dem https://start.spring.io/[spring-initializer] die Abhängigkeiten erneuert werden sollen, kann mit der letzten https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.7.11&packaging=jar&jvmVersion=11&groupId=de.rahn.guidelines.springboot&artifactId=guideline-springboot-parent&name=Parent&description=Guidelines%20for%20Spring%20Boot%20-%20Parent&packageName=de.rahn.guidelines.springboot.parent&dependencies=lombok,configuration-processor,devtools,validation,security,cloud-starter-sleuth,data-jdbc,h2,actuator,hsql,batch,web,hateoas,thymeleaf,data-jpa,jdbc[Konfiguration] verwendet werden.

== Homepage des Autors

https://www.frank-rahn.de/?utm_source=github&utm_medium=readme&utm_campaign=guidelines-spring-boot&utm_content=top[Frank W. Rahn]
