= Guidelines for Spring Boot
Frank Rahn <frank@frank-rahn.de>
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc:
:toclevels: 3
:toc-title: pass:[<h2>Inhaltsverzeichnis</h2>]
:toc-placement!:
:sectanchors:
:sectnums:
:icons: font

image:https://img.shields.io/badge/license-Apache_License_2-blue.svg[title="Apache License 2", alt="Apache License 2", link="https://www.apache.org/licenses/LICENSE-2.0"]
image:https://github.com/frank-rahn/guidelines-spring-boot/workflows/build/badge.svg[title="Build Status",alt="Build Status", link="https://github.com/frank-rahn/guidelines-spring-boot/actions?query=workflow%3Abuild"]
image:https://sonarcloud.io/api/project_badges/measure?project=frank-rahn_guidelines-spring-boot&metric=alert_status[title="Quality Gate Status", alt="Quality Gate Status", link="https://sonarcloud.io/dashboard?id=frank-rahn_guidelines-spring-boot"]

toc::[]

== Beschreibung

In diesem Repository befinden sich Projekte als Vorlagen rund um das Thema Spring Boot.

== Module

In allen Modulen wird der Java Style Guide aus den
link:https://google.github.io/styleguide/[Google Style Guides] genutzt.

=== App-Core

Es wird eine Anwendung gestartet, die einige Dinge erledigt, und sich wieder beendet.
Dabei wird ein entsprechender Exit-Code zurückgeliefert.

Weiterhin werden ...

=== App-JPA

Eine Anwendung mit Datenbankzugriffen ...

=== Batch

Eine Batch-Anwendung ...

=== Rest

Eine Rest-Service ...

=== Web

Eine Webanwendung ...

== Hilfen

link:HELP.adoc[Getting Started]

== Homepage des Autors

https://www.frank-rahn.de/?utm_source=github&utm_medium=readme&utm_campaign=guidelines-spring-boot&utm_content=top[Frank W. Rahn]
