info:
  application:
    name: @project.name@
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@
    description: @project.description@

server:
  port: 8080
  servlet:
    session:
      cookie:
        name: ${info.application.name}_JSESSIONID

spring:
  application:
    name: ${info.application.name}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'