spring:
  application:
    name: @project.name@
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      org:
        hibernate:
          envers:
            audit_table_suffix: _AUDIT
            revision_field_name: REVISION_ID
            revision_type_field_name: REVISION_TYPE
            do_not_audit_optimistic_locking_field: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace