info:
  application:
    name: @project.name@
    description: @project.description@

server:
  port: 8081
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        name: ${info.application.name}_JSESSIONID
  tomcat:
    redirect-context-root: false

spring:
  application:
    name: ${info.application.name}
  jackson:
    serialization:
      indent-output: true

management:
  info:
    java:
      enabled: true
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
      mode: full
    os:
      enabled: true
    defaults:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  show-actuator: true
