name: build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache for Maven
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven und JIB (Docker Image)
        run: mvn --batch-mode --show-version --errors install
      - name: Analyze with SonarCloud
        run: mvn --batch-mode sonar:sonar -Dsonar.host.url=$HOST -Dsonar.organization=$ORG -Dsonar.projectKey=$KEY -Dsonar.login=$LOGIN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOGIN: ${{ secrets.SONAR_LOGIN }}
          HOST: "https://sonarcloud.io"
          ORG: "frank-rahn"
          KEY: "frank-rahn_guidelines-spring-boot"
